app/controller/indexcontroller/article/__init__.py
from app.controller.indexcontroller.blueprint import article
from model.database.db import Article, Comment, db, Articlelike, User
from flask import render_template, request, jsonify, g, session
from sqlalchemy.exc import IntegrityError
import html


@article.route('/article')
def get_article():
    id = request.args.get('id', type=int)
    if id is None:
        return jsonify(code=400, message='Page Not Exist'), 404
    art = Article.query.filter_by(id=id).first()
    art.createtime = art.create_time.strftime('%Y-%m-%d %H:%M:%S')
    if art is None:
        return jsonify(code=400, message='Page Not Exist'), 404
    username = session.get('username')
    if username is None:
        return render_template('article.html', userdata=art.user, art=art)
    user = User.query.filter_by(username=username).first()
    if user is None:
        session.clear()
        return render_template('article.html', userdata=art.user, art=art)

    if Articlelike.query.filter_by(userid=user.id, articleid=id).first() is None:
        return render_template('article.html', userdata=art.user, art=art)
    active = 'active'
    return render_template('article.html', userdata=art.user, art=art, active=active)


@article.route('/comment/add', methods=['POST'])
def addarticle():
    data = request.get_json()
    try:
        article_id = data['article_id']
        content = data['content']
    except KeyError:
        return jsonify(code=400, message='Wrong Parameters')
    userobject = g.get('userObject')
    boolvalue = False
    findcomm = Comment.query.filter_by(articleid=article_id, userid=userobject.id).first()
    if findcomm is None:
        boolvalue = True
    try:
        db.session.add(Comment(articleid=article_id, userid=userobject.id, content=html.escape(content)))
        db.session.commit()
    except IntegrityError:
        return jsonify(code=400, message='Failed to Answer')
    if boolvalue:
        userobject.money = userobject.money + 1

        db.session.commit()
        return jsonify(code=200, message='Answer Submited, +1 point')
    return jsonify(code=200, message='Answer Submited')


@article.route('/getcomment')
def getcomment():
    articleid = request.args.get('article_id', type=int)
    if articleid is None:
        return jsonify(code=400, message='Page Not Exist')
    data = []
    artdata = Comment.query.filter(Comment.articleid == articleid).all()

    for i in artdata:
        data.append(
            {'id': i.id, 'content': i.content, 'user': i.user.username, 'avatar': '/static/photo/' + i.user.photopath})
    return jsonify(code=200, message='Reques Successful', data=data)


@article.route('/like', methods=['POST'])
def clicklick():
    articleid = request.get_json().get('articleid')
    if articleid is None:
        return jsonify(code=400, message='Wrong Parameters')
    userObject = g.get('userObject')
    like = Articlelike.query.filter_by(userid=userObject.id, articleid=articleid)
    if like.first() is None:
        db.session.add(Articlelike(userid=userObject.id, articleid=articleid))
        db.session.commit()
        return jsonify(code=200, message='Like')
    like.delete()
    db.session.commit()
    return jsonify(code=200, message='Unlike')

app/controller/indexcontroller/leaderboard/__init__.py
from flask import render_template, request
from model.database.db import User
from app.controller.indexcontroller.blueprint import board


@board.route('/leaderboard.html')
def leader():
    top_users = User.query.order_by(User.money.desc()).limit(10).all()

    return render_template('leaderboard.html', users=top_users)

app/routes.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session
from flask_login import logout_user, current_user, login_required
from werkzeug.utils import secure_filename

from .forms import RegistrationForm, LoginForm
from model.database.db import db, User, Article, Comment
from sqlalchemy.exc import IntegrityError
from flask import flash
import time
from functools import wraps

main = Blueprint('main', __name__)
auth = Blueprint('auth', __name__)


def my_login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if 'userid' not in session or 'username' not in session:
            return jsonify(code=401, message='Login Required')
        return func(*args, **kwargs)

    return wrapper


@main.route('/')
def index():
    users = User.query.order_by(User.money.desc()).all()
    return render_template('leaderboard.html', users=users)


@main.route('/index')
def index_page():
    tasks = []
    articledata = Article.query.join(User).filter(Article.userid == User.id).order_by(Article.create_time.desc()).all()
    for i in articledata:
        tasks.append(
            {'id': i.id, 'title': i.title, 'content': i.content, 'time': i.create_time.strftime("%Y-%m-%d %H:%M")}
        )
    return render_template('index.html', tasks=tasks)


@main.route('/login')
def main_login():
    type = request.args.get('type', default=1, type=int)
    return render_template('login.html', type=type)


@main.route('/profile')
def profile():
    if 'username' in session:
        username = session['username']
        return render_template('profile.html', username=current_user.username)
    else:
        return redirect(url_for('main_login'))


@main.route('/forgot_password')
def forgot_password():
    return render_template('password.html')


@auth.route('/register', methods=['GET', 'POST'])
def app_register():
    if request.method == 'POST':
        data = request.get_json()
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')

        if not username or not email or not password:
            return jsonify({'code': 400, 'message': 'Please provide all required fields.'}), 200

        if User.query.filter_by(username=username).first():
            return jsonify({'code': 400, 'message': 'User Name Has Been Taken.'}), 200

        if User.query.filter_by(email=email).first():
            return jsonify({'code': 400, 'message': 'Email already exists.'}), 200

        new_user = User(username=username, email=email, password=password)

        db.session.add(new_user)
        db.session.commit()
        session['username'] = new_user.username
        session['userid'] = new_user.id
        session['timestamp'] = time.time()

        return jsonify({'code': 200, 'message': 'User registered successfully.'}), 200
    else:
        return render_template('register.html')


@main.route('/logout')
def logout():
    session.pop('username', None)
    session.pop('userid', None)
    session.pop('timestamp', None)
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/search', methods=['POST'])
def search():
    keyword = request.form.get('keyword')
    sort_order = request.form.get('sortOrder')

    query = Article.query.filter(Article.title.contains(keyword) | Article.content.contains(keyword))

    if sort_order == 'date-newest':
        query = query.order_by(Article.create_time.desc())
    elif sort_order == 'date-oldest':
        query = query.order_by(Article.create_time.asc())

    tasks = query.all()

    results = [
        {'id': task.id, 'title': task.title, 'content': task.content,
         'time': task.create_time.strftime("%Y-%m-%d %H:%M")}
        for task in tasks
    ]

    return render_template('index.html', tasks=results, word=keyword, sort_order=sort_order)


def get_articles_with_comments_from_user(user_id):
    user_comments = Comment.query.filter_by(userid=user_id).all()

    # 获取这些评论相关的文章
    articles = [comment.article for comment in user_comments]

    # 对文章列表进行去重处理
    distinct_articles = list(set(articles))

    return distinct_articles


@main.route('/userinfo', methods=['GET', 'POST'])
@my_login_required
def userinfo():
    username = session.get('username')
    if username is None:
        session.clear()
        return redirect('/login')
    user = User.query.filter_by(username=username).first()
    if user is None:
        session.clear()
        return redirect('/login')
    if request.method == 'POST':
        password = request.form.get('password')
        file = request.files.get('file')
        user = User.query.get(session['userid'])
        if password:
            user.password = password
        if file:
            filename = secure_filename(file.filename)
            file.save(os.path.join('app/static/photo', filename))
            print(filename)
            user.photopath = filename
        db.session.commit()

        return jsonify({'code': 200, 'message': 'Update successful'})
    else:
        tasks = []
        userid = session.get('userid')
        articledata = Article.query.filter_by(userid=userid).all()
        answers_articles = get_articles_with_comments_from_user(userid)
        answers = []
        for i in articledata:
            tasks.append(
                {'id': i.id, 'title': i.title, 'content': i.content, 'time': i.create_time.strftime("%Y-%m-%d %H:%M"),
                 'user': i.user.username})
        for i in answers_articles:
            answers.append(
                {'id': i.id, 'title': i.title, 'content': i.content, 'time': i.create_time.strftime("%Y-%m-%d %H:%M"),
                 'user': i.user.username})
        return render_template('profile.html', data=user, tasks=tasks, answers=answers)


@main.route('/add', methods=['POST'])
@my_login_required
def add_task():
    data = request.get_json()
    title = data.get('title')
    content = data.get('content')
    task = Article(title=title, content=content, userid=session['userid'])
    db.session.add(task)
    db.session.commit()
    return jsonify({'code': 200, 'message': 'Task added successfully'})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}QuestHub{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/5.3/assets/css/docs.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    {% block head %}
        <link rel="stylesheet" href="/static/css/mainpagestyle.css">
    {% endblock %}
</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">QuestHub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasDarkNavbar"
                    aria-controls="offcanvasDarkNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                 aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                            aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/leaderboard.html">Introductory</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if session.username %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, {{ session.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/userinfo">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item nav_login">
                                <a class="nav-link" href="/login">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
{% endblock %}


{% block content %}
{% endblock %}


{% block footer %}
    <footer class="w-100 footer bg-dark text-white py-4 mt-5">
        <div class="container">
            <div class="text-center mt-4">
                © 2024 CITS5505 All rights reserved.
            </div>
        </div>
    </footer>
{% endblock %}
</body>

{% block script %}
{% endblock %}

</html>

app/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <title>Login</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<!-- Navbar part -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">CoinQuest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
            aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/leaderboard.html">Introductory</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if session.username %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, {{ session.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/userinfo">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item nav_login">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="ring">
    <i style="--clr:#00ff0a;"></i>
    <i style="--clr:#ff0057;"></i>
    <i style="--clr:#fffd44;"></i>
    <div class="login">
        <h2>Sign In</h2>
        <div class="inputBx">
            <input type="text" placeholder="Username" id="username">
        </div>
        <div class="inputBx">
            <input type="password" placeholder="Password" id="password">
        </div>
        <div class="inputBx">
            <input type="button" id="login_btn" value="Log In">
        </div>

        <div class="links">
            <!-- <a href="{{ url_for('main.forgot_password') }}">Forgot Password</a> -->
            <a href="{{ url_for('auth.app_register') }}">Register</a>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#login_btn").click(function () {
            var username = $('#username').val();
            var password = $('#password').val();
            $.ajax({
                url: 'http://127.0.0.1:5000/login',
                type: 'POST',
                contentType: "application/json",
                data: JSON.stringify({
                    'username': username,
                    'password': password
                }),
                success: function (data) {
                    if (data.code == 400) {
                        alert(data.message);
                    } else {
                        setTimeout(() => {
                            window.location.href = '../';
                        }, 800);
                    }
                },
                error: (e) => {
                    alert(JSON.stringify(e));
                }
            });
        });
    });
</script>
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/profile.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="p-3 m-0 border-0 bd-example custom-background mt-5">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="./">CoinQuest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/leaderboard.html">Introductory</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if session.username %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, {{ session.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/userinfo">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item nav_login">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-5">
    <div class="row ">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center mb-4" style="font-size: 35px;">Account Information</h1>
                    <div class="text-center mb-4">
                        <img src="{{ url_for('static',filename="photo/"+data.photopath) }}" width="80" height="80"
                             style="border: 3px solid #f2706b;border-radius: 100%;" alt=""/>
                    </div>
                    <div class="row mb-3">
                        <div class="mb-3">
                            <label for="rewards" class="form-label fw-bold">Rewards Points</label>
                            <input type="text" class="form-control" id="rewards" readonly disabled="disabled"
                                   value="{{ data.money }}">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label fw-bold">username</label>
                        <input type="text" class="form-control" id="username" value="{{ data.username }}" disabled>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label fw-bold">Password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               value="{{ data.password }}">
                    </div>

                    <div class="mb-3">
                        <label for="profileImage" class="form-label fw-bold">Profile Image</label>
                        <input type="file" class="form-control" id="profileImage">
                    </div>
                    <button type="button" class="btn btn-primary" onclick="requestajx()">Save Changes</button>
                </div>


            </div>
        </div>
        <div class="col-md-7">

            <div class="card">
                <h1 class="card-title text-center mb-4" style="font-size: 35px;">My Uploads</h1>
                <div class="card-body" style="max-height: 300px; overflow-y: auto;">

                    {% for task in tasks %}
                        <div class="layui-card my-card">
                            <div class="layui-card-body" style="width: 100%;">
                                <a class="card-title" href="/article?id={{ task.id }}">Title: {{ task.title }}</a>
                                <p class="card-text" style="color: black;"><strong>Author: <span
                                        style="color: red;">{{ task.user }}</span></strong>
                                </p>
                                <p class="card-text timestamp"><strong>Timestamp:</strong> {{ task.time }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="card" style="margin-top: 40px;">
                <h1 class="card-title text-center mb-4" style="font-size: 35px;">My Answers</h1>
                <div class="card-body" style="max-height: 300px; overflow-y: auto;">

                    {% for task in answers %}
                        <div class="layui-card my-card">
                            <div class="layui-card-body" style="width: 100%;">
                                <a class="card-title" href="/article?id={{ task.id }}">Title: {{ task.title }}</a>
                                <p class="card-text" style="color: black;"><strong>Author: <span
                                        style="color: red;">{{ task.user }}</span></strong>
                                </p>
                                <p class="card-text timestamp"><strong>Timestamp:</strong> {{ task.time }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>


    </div>
    <hr>
</div>

<script>
    function requestajx() {
        let form = new FormData();
        let password = $('#password').val();
        let file = document.querySelector('input[type="file"]').files[0];
        if (password === '' && file === undefined) {
            alert('Please Enter');
            return;
        }
        if (file !== undefined) {
            form.append('file', file);
        }
        if (password !== '') {
            form.append('password', password);
        }
        console.log(form);
        $.ajax({
            url: '/userinfo',
            method: 'POST',
            data: form,
            processData: false,
            contentType: false,
            success: (res) => {
                if (res.code === 200) {
                    alert('Change Saved');
                    setTimeout(() => {
                        window.location.reload();
                    }, 1000);
                    return;
                }
            },
            error: (e) => {
                alert('Error: ' + JSON.stringify(e));
            }
        });
    }
</script>
</body>
</html>

app/templates/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/profile.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Register</title>
</head>
<body>
<!-- Navbar part -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">CoinQuest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">Menu</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/leaderboard.html">Introductory</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if session.username %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, {{ session.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/userinfo">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item nav_login">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="ring">
    <i style="--clr:#00ff0a;"></i>
    <i style="--clr:#ff0057;"></i>
    <i style="--clr:#fffd44;"></i>
    <div class="login">
        <h2>Register</h2>
        <div class="inputBx">
            <input type="text" placeholder="Username" id="username">
        </div>
        <div class="inputBx">
            <input type="email" placeholder="Email" id="email">
        </div>
        <div class="inputBx">
            <input type="password" placeholder="Password" id="password">
            <!-- <i class="fas fa-eye toggle-password"></i> -->
        </div>
        <div class="inputBx">
            <input type="password" placeholder="Confirm Password" id="confirm_password">
            <!-- <i class="fas fa-eye toggle-password"></i> -->
        </div>
        <div class="inputBx">
            <input type="button" id="register_btn" value="Register">
        </div>
        <div class="links">
            <a href="{{ url_for('lg.login') }}">Back To Login</a>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#register_btn").click(function () {
            var username = $('#username').val();
            var email = $('#email').val();
            var password = $('#password').val();
            var confirm_password = $('#confirm_password').val();
            var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
            if (!emailPattern.test(email)) {
                alert('Please enter a valid email address');
                return;
            }

            if (password !== confirm_password) {
                alert('Passwords do not match');
                return;
            }


            $.ajax({
                url: '/register',
                type: 'POST',
                contentType: "application/json",
                data: JSON.stringify({
                    'username': username,
                    'email': email,
                    'password': password
                }),
                success: function (data) {
                    if (data.code == 400) {
                        console.log(data.message);
                        alert(data.message);
                    } else {
                        alert('Registration Successful!');
                        setTimeout(() => {
                            window.location.href = '../';
                        }, 800);
                    }
                },
                error: function (e) {
                    data = JSON.stringify(e);
                    console.log(data);
                    alert(e.message);
                }
            });
        });
    });
</script>
</body>
</html>